
[build]
  publish = "dist/public"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW"
    Content-Security-Policy = "frame-ancestors *;"
    Feature-Policy = "fullscreen *;"
