
[build]
  publish = "dist/public"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors *; default-src * 'unsafe-inline' 'unsafe-eval'; img-src * data: blob:; connect-src *; worker-src * blob:;"
    Permissions-Policy = "fullscreen=*, geolocation=*, camera=*, microphone=*"
    Access-Control-Allow-Origin = "*"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "unsafe-none"
    Cross-Origin-Resource-Policy = "cross-origin"
