
[build]
  publish = "dist/public"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors *; default-src * 'unsafe-inline' 'unsafe-eval'; img-src * data:; connect-src *;"
    Permissions-Policy = "fullscreen=*, geolocation=*, camera=*, microphone=*"
